<?php if (count($queries = $this->getStep()->getQueries())): ?>
	<div class="queries" id="ENT_profiler_step_<?php echo $this->getStep()->getID(); ?>_queries">
		<div class="tools">
			<a href="" class="query-show-all">show all</a>
			<a href="" class="query-hide-trivial">hide trivial</a>

			<a href="" class="query-hide">hide</a>

			<div class="clear"></div>
		</div>
		<div class="content">
			<?php $x = 0; foreach ($queries as $query): $x++; ?>
				<div class="query <?php if ($x == 1): ?>first<?php endif; ?> <?php if ($this->displayTime($query->getDuration()) < 1): ?>trivial<?php endif; ?>">
					<div class="sql">
						<?php echo $this->parseSql($query->getSql()); ?>
					</div>
	
					<div class="info">
						<div class="toggle">
							<?php echo $this->getStep()->getName(); ?><br />
							<span><?php echo $this->displayTime($query->getDuration()); ?> ms</span><br />
							<?php echo $this->getCRUDType($query->getSql()); ?><br /><br />
						</div>
						<?php if ($this->displayTime($query->getDuration()) < 1): ?>
							<a href="" class="query-toggle" rel="hide">show</a>
						<?php else: ?>
							<a href="" class="query-toggle" rel="show">hide</a>
						<?php endif; ?>
					</div>
	
					<div class="clear"></div>
				</div>
			<?php endforeach; ?>
		</div>
	</div>
<?php endif; ?>
<?php if (count($steps = $this->getStep()->getChildren())): ?>
	<?php foreach ($steps as $step): ?>
		<?php echo $this->displayQuery($step); ?>
	<?php endforeach; ?>
<?php endif; ?>
